[package]
name = "remote-leak"
version = "0.2.0"
authors = ["Alexandre Péré <alexandre.pere@protonmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
liborchestra = { path = "../liborchestra"}