stages:
  - test

before_script:
  - source $HOME/.cargo/env
  - eval `ssh-agent -s`
  - ssh-add

test:
  stage: test
  script:
    - cd $HOME/runaway
    - git checkout $CI_COMMIT_SHA
    - mkdir /tmp/runaway_test
    - rustc --version
    - cargo --version
    - cargo test --tests
  after_script:
    - rm -rf /tmp/runaway-test
  
