stages:
  - test

before_script:
  - source $HOME/.cargo/env
  - eval `ssh-agent -s`
  - ssh-add
  - mkdir /tmp/runaway_test

test:
  stage: test
  only: 
    - develop
  tags:
    - osx
    - linux
  script:
    - rustc --version
    - cargo --version
    - cargo test --tests
  after_script:
    - rm -rf /tmp/runaway_test
  
