[workspace]
members = [
    "liborchestra",
    "runaway-cli",
    "remote-leak"]

[replace]
"liborchestra:0.0.2" = { path = "liborchestra"}
"runaway-cli:0.0.2" = { path = "runaway-cli"}
"remote-leak:0.0.2" = {path = "remote-leak"}
"ssh2:0.3.3" = { path = "ssh2-rs"}