[workspace]
members = [
    "liborchestra",
    "runaway-cli",
#    "remote-leak",
    "ssh2-rs",
    "libssh2-sys"]

[patch.crates-io]
"ssh2" = {path="ssh2-rs"}
"libssh2-sys" = { path = "libssh2-sys"}