[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies]
libssh2-sys = { version="0.2.11", path = "../libssh2-sys" }
libc = "0.1"

[build-dependencies]
ctest = "0.1"
