[package]
name = "liborchestra-derive"
version = "0.0.2"
authors = ["Alexandre Péré <alexandre.pere@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.23"
quote = "0.6.12"